spring.application.name=driver-location-streamer
kafka.bootstrap-servers=kafka:9092
kafka.topics.rider-location=rider.location
kafka.consumers.driver-location-streamer.group-id=driver.location.websocket.group
kafka.listeners.driver-location-streamer.id=driverLocationStreamerListener

server.port=${PORT:0}

eureka.client.serviceUrl.defaultZone=http://discovery:8082/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.devtools.restart.enabled=true
