#Application's name with which the microservice will be registered
#at eureka discovery service dashboard
spring.application.name=location-rider

kafka.bootstrap-servers=kafka:9092

#Quartz config
spring.quartz.jdbc.initialize-schema=always
spring.quartz.job-store-type=memory

spring.datasource.url=jdbc:mysql://mysql:3306/ride_requests_db
spring.datasource.username=microgo_user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#Server port number will receive:
#The value of PORT attribute if it is passed in args
#Otherwise a random port number
server.port=${PORT:0}

#Url of discovery server
eureka.client.serviceUrl.defaultZone=http://discovery:8082/eureka
eureka.client.enabled=false

#Enable devtools to restart the server automatically each time there are code updates
spring.devtools.restart.enabled=true

# eureka.instance.instance-id is used to randomly associate
# a different id for each running instance of the same microservice.
# ${spring.application.instance_id:${random.value}} tells that if no instance_id is passed
# then run the microservice with a random value.
# Use the following command to create an instance of the microservice:
#mvn spring-boot:run -Dspring-boot.run.arguments=--spring.application.instance_id=ANY_VALUE_YOU_CHOOSE
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

#RabbitMQ's connection credentials
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
