spring.application.name=ride-request

kafka.bootstrap-servers=kafka:9092

redis.host=redis
redis.port=6379

spring.datasource.url=jdbc:mysql://mysql:3306/ride_sharing
spring.datasource.username=microgo_user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Server port number will receive:
#The value of PORT attribute if it is passed in args
#Otherwise a random port number
server.port=${PORT:0}

#Url of discovery server
eureka.client.serviceUrl.defaultZone=http://discovery:8082/eureka

#Enable devtools to restart the server automatically each time there are code updates
spring.devtools.restart.enabled=true

# eureka.instance.instance-id is used to randomly associate
# a different id for each running instance of the same microservice.
# ${spring.application.instance_id:${random.value}} tells that if no instance_id is passed
# then run the microservice with a random value.
# Use the following command to create an instance of the microservice:
#mvn spring-boot:run -Dspring-boot.run.arguments=--spring.application.instance_id=ANY_VALUE_YOU_CHOOSE
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

#RabbitMQ's connection credentials
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
