spring.application.name=simulation-service

kafka.bootstrap-servers=kafka:9092

spring.datasource.url=jdbc:postgresql://postgres:5432/simulation_service
spring.datasource.username=microgo_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none

spring.data.redis.host=redis
spring.data.redis.port=6379

simulation-service.passenger.batch-size=25
simulation-service.driver.batch-size=15
simulation-service.max-nearest-drivers=5
simulation-service.default-driver-speed-kph=28.0
simulation-service.default-rain-speed-factor=0.72
simulation-service.default-traffic-factor=0.68

simulation-service.topics.scenario-started=scenario.started
simulation-service.topics.driver-generated=driver.generated
simulation-service.topics.passenger-generated=simulation.passenger.generated
simulation-service.topics.simulated-ride-requested=simulation.ride.requested
simulation-service.topics.driver-accepted=simulation.driver.accepted
simulation-service.topics.driver-refused=simulation.driver.refused
simulation-service.topics.simulation-metrics-updated=simulation.metrics.updated
simulation-service.topics.simulation-completed=simulation.completed
simulation-service.topics.driver-location-updated=driver.location.updated
simulation-service.topics.driver-notified=driver.notified
simulation-service.topics.ride-assigned=ride.assigned
simulation-service.topics.ride-cancelled=ride.cancelled
simulation-service.topics.driver-reached-pickup=driver.reached.pickup
simulation-service.topics.driver-reached-destination=driver.reached.destination

simulation-service.listeners.driver-location-updated.id=simulationDriverLocationListener
simulation-service.listeners.driver-notified.id=simulationDriverNotifiedListener
simulation-service.listeners.ride-assigned.id=simulationRideAssignedListener
simulation-service.listeners.ride-cancelled.id=simulationRideCancelledListener
simulation-service.listeners.driver-reached-pickup.id=simulationDriverReachedPickupListener
simulation-service.listeners.driver-reached-destination.id=simulationDriverReachedDestinationListener

simulation-service.consumers.driver-location-updated.group-id=simulation.service.driver-location.group
simulation-service.consumers.driver-notified.group-id=simulation.service.driver-notified.group
simulation-service.consumers.ride-assigned.group-id=simulation.service.ride-assigned.group
simulation-service.consumers.ride-cancelled.group-id=simulation.service.ride-cancelled.group
simulation-service.consumers.driver-reached-pickup.group-id=simulation.service.driver-reached-pickup.group
simulation-service.consumers.driver-reached-destination.group-id=simulation.service.driver-reached-destination.group

server.port=${PORT:0}

eureka.client.serviceUrl.defaultZone=http://discovery:8082/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
